"""
Deploy Decision Record (DDR) Writer
Generates an immutable audit trail of every deployment attempt,
including the checks run, the policies enforced (via postmortems),
and the final decision.
"""
import os
import json
import datetime
import getpass
import socket


def _get_git_info(project_dir="."):
    """Attempt to extract git info if available."""
    info = {"commit": "unknown", "branch": "unknown", "author": "unknown"}
    try:
        # We don't want to rely on the git binary, so we'll do a quick read
        # of the .git directory if it exists, but this is a best-effort approach.
        # For a robust solution without dependencies, we'd rely on CI env vars.
        
        # Try to use CI env vars first
        if os.environ.get("GITHUB_SHA"):
            info["commit"] = os.environ.get("GITHUB_SHA")[:7]
            info["branch"] = os.environ.get("GITHUB_REF_NAME", "unknown")
            info["author"] = os.environ.get("GITHUB_ACTOR", "unknown")
            return info
            
        if os.environ.get("CI_COMMIT_SHA"):
            info["commit"] = os.environ.get("CI_COMMIT_SHORT_SHA", os.environ.get("CI_COMMIT_SHA")[:7])
            info["branch"] = os.environ.get("CI_COMMIT_BRANCH", "unknown")
            info["author"] = os.environ.get("GITLAB_USER_LOGIN", "unknown")
            return info

        git_dir = os.path.join(project_dir, ".git")
        if os.path.exists(git_dir):
            head_path = os.path.join(git_dir, "HEAD")
            if os.path.exists(head_path):
                with open(head_path, "r") as f:
                    head_ref = f.read().strip()
                    if head_ref.startswith("ref: "):
                        branch = head_ref.split("/")[-1]
                        info["branch"] = branch
                        ref_path = os.path.join(git_dir, head_ref[5:])
                        if os.path.exists(ref_path):
                            with open(ref_path, "r") as rf:
                                info["commit"] = rf.read().strip()[:7]
    except Exception:
        pass
    
    return info


def write_ddr(project, environment, decision, results, overrides=None):
    """
    Write a Deploy Decision Record (DDR) markdown file.
    """
    ddr_dir = "deploy-records"
    if not os.path.exists(ddr_dir):
        try:
            os.makedirs(ddr_dir)
        except Exception:
            return None # Fail silently if we can't write audit logs

    now = datetime.datetime.now(datetime.timezone.utc)
    timestamp_str = now.strftime("%Y-%m-%dT%H:%M:%SZ")
    file_timestamp = now.strftime("%Y%m%d-%H%M%S")
    
    git_info = _get_git_info()
    user = os.environ.get("USER", getpass.getuser())
    host = socket.gethostname()
    
    filename = f"{file_timestamp}-{project}-{environment}-{decision.lower()}.md"
    filepath = os.path.join(ddr_dir, filename)
    
    with open(filepath, "w") as f:
        f.write(f"# Deploy Decision Record: {project} → {environment}\n\n")
        
        f.write("## 📝 Metadata\n")
        f.write(f"- **Date:** {timestamp_str}\n")
        f.write(f"- **Decision:** `{decision}`\n")
        f.write(f"- **Triggered By:** {user}@{host}\n")
        f.write(f"- **Commit:** `{git_info['commit']}` (Branch: `{git_info['branch']}`)\n\n")
        
        f.write("## 🛡️ Checks Executed\n\n")
        f.write("| Check | Status | Details |\n")
        f.write("|---|---|---|\n")
        for check_name, result in results.items():
            icon = "✅" if result["status"] == "PASS" else "❌" if result["status"] == "FAIL" else "⚠️" if result["status"] == "WARN" else "⏭️"
            f.write(f"| {check_name} | {icon} {result['status']} | {result['message']} |\n")
            
        f.write("\n## 🧠 Incident-Trained Policies Enforced\n\n")
        
        incident_result = results.get("Incident Gates", {})
        enforced = incident_result.get("enforced_rules", [])
        
        if enforced:
            f.write("| Policy | Source | Severity | Result |\n")
            f.write("|---|---|---|---|\n")
            for rule in enforced:
                icon = "✅" if rule["status"] == "PASS" else "❌" if rule["status"] == "FAIL" else "ℹ️"
                f.write(f"| {rule['rule']} | `{rule['source']}` | {rule.get('severity', 'unknown')} | {icon} |\n")
        else:
            f.write("*No incident-trained policies were enforced during this deploy.*\n")
            
        f.write("\n---\n")
        f.write(f"*Generated by Graveyard CLI at {timestamp_str}*")

    return filepath
